name: Add screenshots links to pull request
on:
  workflow_run:
    workflows: [tests]
    types: [completed]

jobs:
  screenshots-url-comments:
    name: add screenshots links to pull request
    runs-on: ubuntu-latest
    steps:
      - name: add artifact links to pull request and related issues step
        uses: tonyhallett/artifacts-url-comments@v1.1.0
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            prefix: "This pull request generated screenshots of many common pages in the running app. You should be able to download and view them here: "
            suffix: 
            format: url
            addTo: pull
